version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/contas-api

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: contas-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin